import { ArrowRight, Check, ChevronRight, CircleDotDashed, Gauge, Network, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { BrandMark } from "@/components/AppShell";
const routeCards = [
  { number: "01", title: "Observe", text: "Capacity, outages, revenue, and support load share one clear field.", icon: Gauge },
  { number: "02", title: "Direct", text: "Move from a signal to the exact client, node, invoice, or ticket behind it.", icon: Network },
  { number: "03", title: "Prove", text: "Every operational action leaves an auditable, searchable trace.", icon: ShieldCheck }
];
export default function Marketing() {
  return <div className="min-h-screen overflow-hidden bg-[#f5f6f8] text-[#14213d]">
    <header className="relative z-10 flex items-center justify-between px-5 py-5 sm:px-8 lg:px-14 lg:py-7">
      <Link href="/" aria-label="Northline home"><BrandMark /></Link>
      <nav className="hidden items-center gap-7 text-xs font-bold text-[#5e6b82] md:flex" aria-label="Marketing navigation"><a href="#system" className="hover:text-[#1758e8]">System</a><a href="#workflows" className="hover:text-[#1758e8]">Workflows</a><a href="#coverage" className="hover:text-[#1758e8]">Coverage</a></nav>
      <div className="flex items-center gap-2.5"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-xs font-bold text-[#536079] transition hover:bg-white sm:block">Operator login</Link><Link href="/register" className="rounded-xl bg-[#1758e8] px-4 py-2.5 text-xs font-bold text-white shadow-[0_10px_22px_rgba(23,88,232,0.24)] transition hover:-translate-y-0.5 hover:bg-[#134dd0] active:scale-[0.97]">Build your field</Link></div>
    </header>

    <main>
      <section className="relative mx-auto max-w-[1500px] px-5 pb-16 pt-5 sm:px-8 lg:px-14 lg:pb-24 lg:pt-12">
        <div className="absolute left-0 top-8 hidden h-px w-[17%] bg-[#cad3e3] lg:block" />
        <div className="grid items-stretch gap-8 lg:grid-cols-[0.86fr_1.14fr] lg:gap-14">
          <div className="relative z-10 flex flex-col justify-center py-4 lg:py-12">
            <p className="mb-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.22em] text-[#1758e8]"><span className="inline-block h-5 w-[3px] bg-[#1758e8]" />ISP operating system / wireframe</p>
            <h1 className="max-w-[620px] text-[clamp(2.7rem,6vw,5.8rem)] font-bold leading-[0.92] tracking-[-0.075em] text-[#15213d]">Read every <span className="text-[#1758e8]">signal.</span><br />Run every route.</h1>
            <p className="mt-7 max-w-lg text-base leading-7 text-[#657187] sm:text-lg">Northline joins network health, subscriber records, support, and revenue operations into one unambiguous command center.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="group inline-flex items-center gap-3 rounded-xl bg-[#14213d] px-5 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#223253] active:scale-[0.97]">Explore the command center <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link><a href="#system" className="inline-flex items-center gap-2 rounded-xl border border-[#cfd8e7] bg-white px-5 py-3.5 text-sm font-bold text-[#536079] transition hover:border-[#9eafd0] hover:text-[#1758e8]">See the system <ChevronRight className="h-4 w-4" /></a></div>
            <div className="mt-12 grid max-w-lg grid-cols-3 border-t border-[#dce2eb] pt-5"><div><p className="text-2xl font-bold tracking-[-0.06em] tabular-nums">01</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.15em] text-[#7b869a]">Signal field</p></div><div><p className="text-2xl font-bold tracking-[-0.06em] tabular-nums">09</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.15em] text-[#7b869a]">Core views</p></div><div><p className="text-2xl font-bold tracking-[-0.06em] tabular-nums">1:1</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.15em] text-[#7b869a]">Audit route</p></div></div>
          </div>
          <div className="relative min-h-[440px] overflow-hidden rounded-[28px] border border-[#263657] bg-[#14213d] shadow-[0_26px_70px_rgba(26,40,70,0.22)] lg:min-h-[600px]">
            <img src="/manus-storage/signal-atlas-hero_69e82312.png" alt="Abstract fiber routing field" className="absolute inset-0 h-full w-full object-cover opacity-90" />
            <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,33,61,0.76),rgba(20,33,61,0.08)_70%)]" />
            <div className="absolute left-6 top-6 flex items-center gap-2 rounded-full border border-white/15 bg-[#172746]/75 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-white/75 backdrop-blur"><CircleDotDashed className="h-3.5 w-3.5 text-[#6ee7c8]" /> Live system map</div>
            <div className="absolute bottom-6 left-6 right-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-[#182846]/85 p-4 text-white backdrop-blur"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-white/50">Subscribers online</p><p className="mt-2 text-2xl font-bold tracking-[-0.055em]">18,246</p><p className="mt-2 flex items-center gap-1 text-[10px] font-bold text-[#6ee7c8]"><span className="h-1.5 w-1.5 rounded-full bg-[#6ee7c8]" /> 96.8% live</p></div><div className="rounded-2xl border border-white/10 bg-[#182846]/85 p-4 text-white backdrop-blur"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-white/50">Capacity alert</p><p className="mt-2 text-2xl font-bold tracking-[-0.055em]">03</p><p className="mt-2 flex items-center gap-1 text-[10px] font-bold text-[#f6bb59]"><span className="h-1.5 w-1.5 rounded-full bg-[#f6bb59]" /> East / edge 07</p></div><div className="rounded-2xl border border-white/10 bg-[#182846]/85 p-4 text-white backdrop-blur"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-white/50">Revenue in motion</p><p className="mt-2 text-2xl font-bold tracking-[-0.055em]">$88.4k</p><p className="mt-2 flex items-center gap-1 text-[10px] font-bold text-[#a9c0ff]"><span className="h-1.5 w-1.5 rounded-full bg-[#a9c0ff]" /> Reconcile today</p></div></div>
            <div className="absolute right-6 top-6 hidden h-14 w-14 items-center justify-center rounded-full border border-white/15 bg-white/10 text-[#6ee7c8] backdrop-blur sm:flex"><Sparkles className="h-5 w-5" /></div>
          </div>
        </div>
      </section>

      <section id="system" className="border-y border-[#e0e5ed] bg-white px-5 py-16 sm:px-8 lg:px-14 lg:py-24"><div className="mx-auto max-w-[1400px]"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#1758e8]">A shared operating field</p><h2 className="mt-4 max-w-md text-4xl font-bold leading-[0.98] tracking-[-0.06em] text-[#15213d]">From one warning to the exact work it needs.</h2></div><div className="grid gap-4 sm:grid-cols-3">{routeCards.map(({ number, title, text, icon: Icon }) => <article key={number} className="relative overflow-hidden rounded-2xl border border-[#e1e6ee] bg-[#fbfcfe] p-5 transition hover:-translate-y-1 hover:border-[#c2d2f3] hover:shadow-[0_16px_30px_rgba(26,40,70,0.07)]"><p className="text-[10px] font-bold tracking-[0.18em] text-[#1758e8]">{number}</p><span className="mt-7 grid h-10 w-10 place-items-center rounded-xl bg-[#eaf0ff] text-[#1758e8]"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-bold tracking-[-0.04em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6c7890]">{text}</p><div className="absolute bottom-0 left-5 right-5 h-px bg-[#d6deed]" /></article>)}</div></div></div></section>

      <section id="coverage" className="mx-auto grid max-w-[1500px] items-center gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:px-14 lg:py-24"><div className="overflow-hidden rounded-[26px] border border-[#dce3ee] bg-[#eaf0f5] shadow-[0_18px_45px_rgba(28,42,75,0.08)]"><img src="/manus-storage/service-coverage-illustration_1696683b.png" alt="Abstract community fiber coverage field" className="h-full min-h-[260px] w-full object-cover" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#1758e8]">Built for the full route</p><h2 className="mt-4 text-4xl font-bold leading-[0.98] tracking-[-0.06em] text-[#15213d]">The business view and the network view finally agree.</h2><ul className="mt-7 space-y-4">{["Landing, login, and registration paths for a coherent first impression.", "A purpose-built command rail for clients, packages, billing, and support.", "Signal-led charts and network visuals where an operator must scan fast."].map((text) => <li key={text} className="flex gap-3 text-sm leading-6 text-[#637087]"><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#e5f7f1] text-[#168263]"><Check className="h-3 w-3" /></span>{text}</li>)}</ul><Link href="/register" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#1758e8] transition hover:gap-3">Start the wireframe tour <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
    <footer className="border-t border-[#dfe5ee] bg-[#14213d] px-5 py-8 text-white sm:px-8 lg:px-14"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><BrandMark inverse /><p className="text-xs text-white/55">ISP Command Center · Wireframe prototype</p><Link href="/dashboard" className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold text-white transition hover:bg-white/15">Open demo</Link></div></footer>
  </div>;
}
